**Цели работы:**

1. Докажите, что транспонирование транспонированной матрицы - это сама матрица: $(\mathbf{A}^\top)^\top = \mathbf{A}$.

In [1]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

A_transposed = A.T  # Первое транспонирование
A_transposed_transposed = A_transposed.T  # Второе транспонирование

print("Исходная матрица A:\n", A)
print("Транспонированная дважды:\n", A_transposed_transposed)
print("Эквивалентность:", np.array_equal(A, A_transposed_transposed))

Исходная матрица A:
 [[1 2 3]
 [4 5 6]]
Транспонированная дважды:
 [[1 2 3]
 [4 5 6]]
Эквивалентность: True


2. Для двух матриц $\mathbf{A}$ и $\mathbf{B}$, покажите, что сумма и транспозиция коммутируют: $\mathbf{A}^\top + \mathbf{B}^\top = (\mathbf{A} + \mathbf{B})^\top$.


In [2]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

left_side = A.T + B.T
right_side = (A + B).T

print("A^T + B^T:\n", left_side)
print("(A + B)^T:\n", right_side)
print("Эквивалентность:", np.array_equal(left_side, right_side))

A^T + B^T:
 [[ 6 10]
 [ 8 12]]
(A + B)^T:
 [[ 6 10]
 [ 8 12]]
Эквивалентность: True


3. Для любой квадратичной матрицы $\mathbf{A}$, сумма матриц $\mathbf{A} + \mathbf{A}^\top$ всегда ли симметрична? Можете ли вы доказать это, используя только предыдущие два упражнения?

In [3]:
A = np.array([[1, 2], [3, 4]])
S = A + A.T

print("A + A^T:\n", S)
print("Является ли симметричной:", np.array_equal(S, S.T))

A + A^T:
 [[2 5]
 [5 8]]
Является ли симметричной: True


4. Мы определяли тензор `X` размерности (2, 3, 4). Что возвращает функция `len(X)`? Попробуйте записать ответ используя воображение, потом проверьте свой ответ в среде программирования.


In [4]:
X = np.random.rand(2, 3, 4)
print("Форма X:", X.shape)
print("len(X):", len(X))  # Возвращает 2

Форма X: (2, 3, 4)
len(X): 2


5. Для тензора X произвольной размерности, всегда ли функция len(X) возвращает длину тензора по оси X? Что такое ось?


6. Запустите следующий фрагмент кода A / A.sum(axis=1) и проверьте полученный результат.

In [5]:
A = np.array([[1, 2], [3, 4]])
result = A / A.sum(axis=1, keepdims=True)  # Нормировка по строкам
print(result)

[[0.33333333 0.66666667]
 [0.42857143 0.57142857]]


7. Рассмотрим тензор размерности (2, 3, 4). Какие размерности можно получить при суммирования элементов тензора по осям 0, 1 и 2?


In [6]:
X = np.random.rand(2, 3, 4)
print("sum(axis=0):", X.sum(axis=0).shape)
print("sum(axis=1):", X.sum(axis=1).shape)
print("sum(axis=2):", X.sum(axis=2).shape)

sum(axis=0): (3, 4)
sum(axis=1): (2, 4)
sum(axis=2): (2, 3)


8. Передайте тензор с 3 или более осями в функцию linalg.norm и наблюдайте за его выводом.

In [7]:
X = np.random.rand(2, 3, 4)
norm = np.linalg.norm(X)  # Фробениусова норма (корень из суммы квадратов)
print(norm)

2.810285427769023


9. Определите 3 матрицы  A∈R210×216 ,  B∈R216×25  и  C∈R25×214 , содержащие случайные переменные, распределенные по нормальному закону распределения. Вычислите произведение матриц:  ABC .


In [8]:
A = np.random.randn(210, 216)
B = np.random.randn(216, 25)
C = np.random.randn(25, 214)

ABC = A @ B @ C
print("Форма ABC:", ABC.shape)  # (210, 214)

Форма ABC: (210, 214)


10. Определите 3 матрицы  A∈R210×216 ,  B∈R216×25  and  C∈R25×216. Вычисление A @ B сравнить A @ C.T


In [9]:
A = np.random.randn(210, 216)
B = np.random.randn(216, 25)
C = np.random.randn(25, 216)

AB = A @ B
AC_T = A @ C.T
print("Форма AB:", AB.shape)  # (210, 25)
print("Форма AC_T:", AC_T.shape)  # (210, 25)

Форма AB: (210, 25)
Форма AC_T: (210, 25)


11. Определите 3 матрицы  A,B,C∈R100×200 . Сформируйте тензор с 3-мя осями путем объединения матриц  [A,B,C] .

In [10]:
A = np.random.rand(100, 200)
B = np.random.rand(100, 200)
C = np.random.rand(100, 200)

tensor = np.stack([A, B, C])  # Форма (3, 100, 200)
print("Форма тензора:", tensor.shape)

Форма тензора: (3, 100, 200)
